Updates for deployer integration testing. * Corrects start, stop, status RPM behavior * Adds call for preremove control script * Corrects POM formatting issue

diff --git a/blazegraph-rpm/src/rpm/init.d/blazegraph b/blazegraph-rpm/src/rpm/init.d/blazegraph
--- a/blazegraph-rpm/src/rpm/init.d/blazegraph
+++ b/blazegraph-rpm/src/rpm/init.d/blazegraph
@@ -95,7 +95,7 @@ OPENJDKS=""
 find_openjdks
 # The first existing directory is used for JAVA_HOME (if JAVA_HOME is not
 # defined in $DEFAULT)
-JDK_DIRS="/usr/lib/jvm/default-java ${OPENJDKS} /usr/lib/jvm/java-6-openjdk /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-7-oracle /usr/lib/jvm/java-8-oracle"
+JDK_DIRS="/usr/lib/jvm/default-java ${OPENJDKS} /usr/lib/jvm/java-6-openjdk /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-7-oracle /usr/lib/jvm/java-8-oracle /usr/java/current /usr/bin"
 
 # Look for the right JVM to use
 for jdir in $JDK_DIRS; do
@@ -158,7 +158,7 @@ blazegraph_sh() {
 		BLZG_BASE=\"$BLZG_BASE\"; \
 		JAVA_OPTS=\"$JAVA_OPTS\"; \
 		BLZG_PID=\"$BLZG_PID\"; \
-		BLZG_LOG=\"$BLZG_LOG\"/blazegraph.out; \
+		BLZG_LOG=\"$BLZG_LOG\"/blazegraph.log; \
 		BLZG_TMPDIR=\"$BLZG_TMPDIR\"; \
 		LANG=\"$LANG\"; JSSE_HOME=\"$JSSE_HOME\"; \
 		cd \"$BLZG_BASE\"; \
@@ -170,9 +170,9 @@ blazegraph_sh() {
 	$SU - $BLZG_USER -c "$BLZGCMD_SH start"
 	status="$?"
 
-	if [ $status -gt 0 ] ; then
+	if [ $status -eq 0 ] ; then
 		PID=`cat $BLZG_PID`
-		echo "Started $NAME (pid: $PID)"
+		echo "Started $DESC $NAME (pid ${PID})"
 	fi
 
 	set +a -e
@@ -182,15 +182,14 @@ blazegraph_sh() {
 running_pid() {
 
 	if [ ! -f "${BLZG_PID}" ] ; then
-		return 0;
-                exit 0
+		echo 0;
 	fi
 
 	PID=`cat ${BLZG_PID}`
 
 	let HAS_PID=`ps -eo pid | grep $PID | wc -l`
 
-	return ${HAS_PID} 
+	echo ${HAS_PID} 
 	#1 if running, 0 if not
 
 }
@@ -202,9 +201,15 @@ case "$1" in
 		exit 1
 	fi
 
-	if [ ! -d "$BLZG_BASE/conf" ]; then
-		echo "invalid BLZG_BASE: $BLZG_BASE"
+	if [ ! -d "$BLZG_CONF" ]; then
+		echo "invalid BLZG_CONF: $BLZG_CONF"
 		exit 1
+	fi
+
+	if [ "`running_pid`" -eq 1 ] ; then
+		PID=`cat "${BLZG_PID}"`	
+		echo "$DESC $NAME is already running (pid:  $PID)."
+		exit 0
 	fi
 
 	echo "Starting $DESC" "$NAME"
@@ -216,8 +221,9 @@ case "$1" in
 	}
 	chown $BLZG_USER "$JVM_TMP"
 	blazegraph_sh start 
-
+	status=$?
 	sleep 1
+	exit $status
 	;;
   stop)
 	echo "Stopping $DESC" "$NAME"
@@ -227,16 +233,16 @@ case "$1" in
 
 		PID=`cat "${BLZG_PID}"`	
 	
-		if [ `running_pid` -eq 1 ] ; then
+		if [ "`running_pid`" -eq 1 ] ; then
 
 			kill -9 $PID
 			if [ `running_pid` -eq 0 ] ; then
 				rm -f "${BLZG_PID}"
 				rm -rf "$JVM_TMP"
-				echo "Stopped $NAME (pid ${PID})"
+				echo "Stopped $DESC $NAME (pid ${PID})"
 				exit 0
 			else
-				echo "Failed to stop $NAME (pid ${PID})"
+				echo "Failed to stop $DESC $NAME (pid ${PID})"
 				exit 1
 			fi
 		fi
@@ -250,7 +256,7 @@ case "$1" in
    status)
 	set +e
 
-	if [ -f "${BLZG_PID}" ] &&  [ `running_pid` -eq 0 ]; then
+	if [ -f "${BLZG_PID}" ] &&  [ "`running_pid`" -eq 0 ]; then
 	    echo "$DESC is not running, but pid file exists."
 	    exit 3
 	elif [ ! -f "$BLZG_PID" ]; then
