modified to only obtain the log file lock when there is a reason to use it (basically, double-checked locking)
git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/trunk@1613 8f7bc0f5-282e-0410-95e3-8d296e9bb460

diff --git a/src/resources/scripts/bigdata b/src/resources/scripts/bigdata
--- a/src/resources/scripts/bigdata
+++ b/src/resources/scripts/bigdata
@@ -107,34 +107,37 @@ fi
 # Verify site-specific preconditions.
 ./bigdataprecond
 
-# Figure out if this is the master (can create files and set their perms)
+# Create the various log files and set their permissions.
 #
-# @todo not permitted to change the owner or _group_ unless root?
+# Note: this will often result in an error message when the user is
+# not root as some users are not allowed to change the group
+# associated with a file.
 #
 #if [ "$MASTER" == "`hostname`" ]; then
-lockfile -r 1 -1 "$logLockFile"
-if [ 0 == $? ]; then
+if [ ! -f "$eventLog" -o ! -f "$errorLog" -o ! -f "$detailLog" ]; then
+    lockfile -r 1 -1 "$logLockFile"
+    if [ 0 == $? ]; then
 # Event log (where events generated by each service or client get logged).
-    if [ ! -f "$eventLog" ]; then
-	echo $"`date` : `hostname` : creating event log."
-	touch $eventLog
-	chgrp $INSTALL_GROUP $eventLog
-	chmod g+rw $eventLog
-    fi
+	if [ ! -f "$eventLog" ]; then
+	    echo $"`date` : `hostname` : creating event log."
+	    touch $eventLog
+	    chgrp $INSTALL_GROUP $eventLog
+	    chmod g+rw $eventLog
+	fi
 # Error log (where ERROR and above is logged by each service or client).
-    if [ ! -f "$errorLog" ]; then
-	echo $"`date` : `hostname` : creating error log."
-	touch $errorLog
-	chgrp $INSTALL_GROUP $errorLog
-	chmod g+rw $errorLog
-    fi
+	if [ ! -f "$errorLog" ]; then
+	    echo $"`date` : `hostname` : creating error log."
+	    touch $errorLog
+	    chgrp $INSTALL_GROUP $errorLog
+	    chmod g+rw $errorLog
+	fi
 # Detail log (where INFO and above is logged by each service or client).
-    if [ ! -f "$detailLog" ]; then
-	echo $"`date` : `hostname` : creating detail log."
-	touch $detailLog
-	chgrp $INSTALL_GROUP $detailLog
-	chmod g+rw $detailLog
-    fi
+	if [ ! -f "$detailLog" ]; then
+	    echo $"`date` : `hostname` : creating detail log."
+	    touch $detailLog
+	    chgrp $INSTALL_GROUP $detailLog
+	    chmod g+rw $detailLog
+	fi
 #else
 #    if [ ! -w "$eventLog" ]; then
 #	echo $"`date` : `hostname` : warning: can not write event log."
@@ -144,7 +147,8 @@ if [ 0 == $? ]; then
 #	echo $"`date` : `hostname` : warning: can not write error log."
 ##	exit 1
 #    fi
-    rm -f "$logLockFile"
+	rm -f "$logLockFile"
+    fi
 fi
 
 #
@@ -222,27 +226,28 @@ case "$1" in
 	    echo $"`date` : `hostname` : destroying data."
 	    rm -rf "$LAS"
 	fi
-	lockfile -r 1 -1 "$logLockFile"
-	if [ 0 == $? ]; then
+	if [ -s "$eventLog" -o -s "$errorLog" -o -s "$detailLog" ]; then
+	    lockfile -r 1 -1 "$logLockFile"
+	    if [ 0 == $? ]; then
 #           Granted lock in the log directory so we can rename the log
 #           files.
 #	if [ "$MASTER" == "`hostname`" ]; then
 #           Move the event log out of the way (exists and is not empty).
-	    random=`date +%N | sed -e 's/000$//' -e 's/^0//'`
-	    if [ -s "$eventLog" ]; then
-		echo $"`date` : `hostname` : renaming old event log."
-		mv "$eventLog" "$eventLog-`date +%F`$random.old"
-	    fi
+		random=`date +%N | sed -e 's/000$//' -e 's/^0//'`
+		if [ -s "$eventLog" ]; then
+		    echo $"`date` : `hostname` : renaming old event log."
+		    mv "$eventLog" "$eventLog-`date +%F`$random.old"
+		fi
 #           Move the error log out of the way (exists and is not empty).
-	    if [ -s "$errorLog" ]; then
-		echo $"`date` : `hostname` : renaming old error log."
-		mv "$errorLog" "$errorLog-`date +%F`$random.old"
-	    fi
+		if [ -s "$errorLog" ]; then
+		    echo $"`date` : `hostname` : renaming old error log."
+		    mv "$errorLog" "$errorLog-`date +%F`$random.old"
+		fi
 #           Move the services log out of the way (exists and is not empty).
-	    if [ -s "$detailLog" ]; then
-		echo $"`date` : `hostname` : renaming old services log."
-		mv "$detailLog" "$detailLog-`date +%F`$random.old"
-	    fi
+		if [ -s "$detailLog" ]; then
+		    echo $"`date` : `hostname` : renaming old services log."
+		    mv "$detailLog" "$detailLog-`date +%F`$random.old"
+		fi
 ## @todo add a bigdatadestroy hook and then this stuff can go into that file.
 ##
 ## Delete performance counter snapshots from the load balancer.
@@ -257,7 +262,8 @@ case "$1" in
 ##		echo $"`date` : `hostname` : removing index dumps."
 ##		rm -rf /opt2/trials/indexDumps
 ##	    fi
-	    rm -f "$logLockFile"
+		rm -f "$logLockFile"
+	    fi
 	fi
         ;;
     hup)
