removed "MASTER" property - now using lockfile to guard process renaming the log files.
git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/trunk@1611 8f7bc0f5-282e-0410-95e3-8d296e9bb460

diff --git a/src/resources/scripts/bigdata b/src/resources/scripts/bigdata
--- a/src/resources/scripts/bigdata
+++ b/src/resources/scripts/bigdata
@@ -62,6 +62,9 @@
 # will echo 'locked' iff the lock was obtained.  The test can be changed
 # to if [ 0 != $? ] to reverse the semantics.
 #
+# Note: when run as root we can use the standard subsystem lock file
+# but not when run as a normal user.
+#
 # @todo rollover log files every day and keep only N days worth (probably
 # needs to be done within log4j for its log files and in cron for the state.log
 # file.
@@ -85,10 +88,10 @@ cd `dirname $0`
 source ./bigdataenv
 
 # Verify critical environment variables.
-if [ -z "$MASTER" ]; then
-	echo -n $"$0 : environment not setup."
-	exit 1
-fi
+#if [ -z "$MASTER" ]; then
+#	echo -n $"$0 : environment not setup."
+#	exit 1
+#fi
 if [ -z "$lockFile" ]; then
 	echo -n $"$0 : environment not setup."
 	exit 1;
@@ -101,44 +104,42 @@ fi
 # Verify site-specific preconditions.
 ./bigdataprecond
 
-# @todo not permitted to change the owner or _group_ unless root. Also,
-# when run as root we can use the standard subsystem lock file but not
-# when run as a normal user.
-#
 # Figure out if this is the master (can create files and set their perms)
-if [ "$MASTER" == "`hostname`" ]; then
-# Event log (where events are written by each service or client).
+#
+# @todo not permitted to change the owner or _group_ unless root?
+#
+#if [ "$MASTER" == "`hostname`" ]; then
+# Event log (where events generated by each service or client get logged).
     if [ ! -f "$eventLog" ]; then
 	echo $"`date` : `hostname` : creating event log."
 	touch $eventLog
-#	chgrp $INSTALL_GROUP $eventLog
+	chgrp $INSTALL_GROUP $eventLog
 	chmod g+rw $eventLog
     fi
 # Error log (where ERROR and above is logged by each service or client).
     if [ ! -f "$errorLog" ]; then
 	echo $"`date` : `hostname` : creating error log."
 	touch $errorLog
-#	chgrp $INSTALL_GROUP $errorLog
+	chgrp $INSTALL_GROUP $errorLog
 	chmod g+rw $errorLog
     fi
-# Detail log (all aggregated log messages from each service or client).
-# Note that a single runLog4jServer.sh must be running to log on this file.
+# Detail log (where INFO and above is logged by each service or client).
     if [ ! -f "$detailLog" ]; then
 	echo $"`date` : `hostname` : creating detail log."
 	touch $detailLog
-#	chgrp $INSTALL_GROUP $detailLog
+	chgrp $INSTALL_GROUP $detailLog
 	chmod g+rw $detailLog
     fi
-else
-    if [ ! -w "$eventLog" ]; then
-	echo $"`date` : `hostname` : can not write event log."
-	exit 1
-    fi
-    if [ ! -w "$errorLog" ]; then
-	echo $"`date` : `hostname` : can not write error log."
-	exit 1
-    fi
-fi
+#else
+#    if [ ! -w "$eventLog" ]; then
+#	echo $"`date` : `hostname` : warning: can not write event log."
+##	exit 1
+#    fi
+#    if [ ! -w "$errorLog" ]; then
+#	echo $"`date` : `hostname` : warning: can not write error log."
+##	exit 1
+#    fi
+#fi
 
 #
 # See how we were called.
@@ -215,42 +216,43 @@ case "$1" in
 	    echo $"`date` : `hostname` : destroying data."
 	    rm -rf "$LAS"
 	fi
-	if [ "$MASTER" == "`hostname`" ]; then
-# Move the event log out of the way (exists and is not empty).
+	lockfile -r 1 -1 "$logDir/renameLogs.lock"
+	if [ 0 == $? ]; then
+#           Granted lock in the log directory so we can rename the log
+#           files.
+#	if [ "$MASTER" == "`hostname`" ]; then
+#           Move the event log out of the way (exists and is not empty).
 	    random=`date +%N | sed -e 's/000$//' -e 's/^0//'`
 	    if [ -s "$eventLog" ]; then
 		echo $"`date` : `hostname` : renaming old event log."
 		mv "$eventLog" "$eventLog-`date +%F`$random.old"
 	    fi
-# Move the error log out of the way (exists and is not empty).
+#           Move the error log out of the way (exists and is not empty).
 	    if [ -s "$errorLog" ]; then
 		echo $"`date` : `hostname` : renaming old error log."
 		mv "$errorLog" "$errorLog-`date +%F`$random.old"
 	    fi
-# Move the services log out of the way (exists and is not empty).
+#           Move the services log out of the way (exists and is not empty).
 	    if [ -s "$detailLog" ]; then
 		echo $"`date` : `hostname` : renaming old services log."
 		mv "$detailLog" "$detailLog-`date +%F`$random.old"
 	    fi
-# @todo add a bigdatadestroy hook and then this stuff can go into that file.
-# Delete performance counter snapshots from the load balancer.
-#	    if [ -d "/opt2/var/log/bigdata" ]; then
-#		echo $"`date` : `hostname` : removing LBS logs."
-#		rm -f /opt2/var/log/bigdata/events.jnl
-#		rm -f /opt2/var/log/bigdata/counters*
-#		rmdir /opt2/var/log/bigdata/
-#	    fi
-# Delete index partition metadata dumps from the data loader.
-#	    if [ -d /opt2/trials/indexDumps ]; then
-#		echo $"`date` : `hostname` : removing index dumps."
-#		rm -rf /opt2/trials/indexDumps
-#	    fi
+## @todo add a bigdatadestroy hook and then this stuff can go into that file.
+##
+## Delete performance counter snapshots from the load balancer.
+##	    if [ -d "/opt2/var/log/bigdata" ]; then
+##		echo $"`date` : `hostname` : removing LBS logs."
+##		rm -f /opt2/var/log/bigdata/events.jnl
+##		rm -f /opt2/var/log/bigdata/counters*
+##		rmdir /opt2/var/log/bigdata/
+##	    fi
+## Delete index partition metadata dumps from the data loader.
+##	    if [ -d /opt2/trials/indexDumps ]; then
+##		echo $"`date` : `hostname` : removing index dumps."
+##		rm -rf /opt2/trials/indexDumps
+##	    fi
+	    rm -f "$logDir/renameLogs.lock"
 	fi
-# Remove the subsystem lock file (done by bigdatadown).
-#	if [ -f "$lockFile" ]; then
-#	    echo $"`date` : `hostname` : destroying lock."
-#	    rm -f "$lockFile"
-#	fi
         ;;
     hup)
 #
