typo when introducing the rule execution log
git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/trunk@1808 8f7bc0f5-282e-0410-95e3-8d296e9bb460

diff --git a/src/resources/scripts/bigdata b/src/resources/scripts/bigdata
--- a/src/resources/scripts/bigdata
+++ b/src/resources/scripts/bigdata
@@ -112,7 +112,7 @@ fi
 # not root as some users are not allowed to change the group
 # associated with a file.
 #
-if [ ! -f "$eventLog" -o ! -f "$errorLog" -o ! -f "$detailLog" -o -f "$ruleLog" ]; then
+if [ ! -f "$eventLog" -o ! -f "$errorLog" -o ! -f "$detailLog" -o ! -f "$ruleLog" ]; then
     lockfile -r 1 -1 "$logLockFile"
     if [ 0 == $? ]; then
 # Event log (where events generated by each service or client get logged).
@@ -144,6 +144,9 @@ if [ ! -f "$eventLog" -o ! -f "$errorLog" -o ! -f "$detailLog" -o -f "$ruleLog" 
 	    chmod g+rw,o-rw $detailLog
 	fi
 	rm -f "$logLockFile"
+    else
+	echo $"`date` : `hostname` : could not obtain lock: $logLogFile"
+	exit 1;
     fi
 fi
 
@@ -228,7 +231,7 @@ case "$1" in
 	    if [ 0 == $? ]; then
 #           Granted lock in the log directory so we can rename the log
 #           files.
-        rm -f $detailLog ${detailLog}.* $errorLog ${errorLog}.* $eventLog $eventLog.* $ruleLog $ruleLog.*
+		rm -f $detailLog ${detailLog}.* $errorLog ${errorLog}.* $eventLog $eventLog.* $ruleLog $ruleLog.*
 		rm -f "$logLockFile"
 	    fi
 	fi
