Added a $BD_USER and $BD_GROUP environment variable for the user & group that will run the bigdataHA instance.
git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/BIGDATA_RELEASE_1_3_0@8107 8f7bc0f5-282e-0410-95e3-8d296e9bb460

diff --git a/src/resources/etc/init.d/bigdataHA b/src/resources/etc/init.d/bigdataHA
--- a/src/resources/etc/init.d/bigdataHA
+++ b/src/resources/etc/init.d/bigdataHA
@@ -31,7 +31,7 @@ else
         STRING=$1
         echo -n "$STRING "
         shift
-        sudo -u bigdata -g bigdata "$@" && echo -n "[OK]" || echo -n "[FAILED]"
+        "$@" && echo -n "[OK]" || echo -n "[FAILED]"
         rc=$?
         echo
         return $rc
@@ -59,6 +59,14 @@ if [ -z "$pidFile" ]; then
    echo $"$0 : environment not setup: pidFile is undefined"
    exit 1;
 fi
+if [ -z "$BD_USER" ]; then
+   echo $"$0 : environment not setup: BD_USER is undefined"
+   exit 1;
+fi
+if [ -z "$BD_GROUP" ]; then
+   echo $"$0 : environment not setup: BD_GROUP is undefined"
+   exit 1;
+fi
 
 cd $FED_DIR
 
@@ -81,7 +89,7 @@ case "$1" in
 	    fi
 	fi
 	if [ ! -f "$pidFile" ]; then
-		action $"`date` : `hostname` : bringing up services: " $binDir/startHAServices
+		action $"`date` : `hostname` : bringing up services: " sudo -u $BD_USER -g $BD_GROUP $binDir/startHAServices
 	else
             echo $"`date` : `hostname` : running as $pid"
 	fi 
@@ -98,7 +106,7 @@ case "$1" in
 		echo $"`date` : `hostname` : $pid died?"
 		rm -f "$pidFile"
 	    else
-		action $"`date` : `hostname` : bringing down services: " kill $pid
+		action $"`date` : `hostname` : bringing down services: " sudo -u $BD_USER -g $BD_GROUP kill $pid
 		rm -f "$pidFile"
 	    fi
 	fi
