update to run actions under the "bigdata" user and group.  actions are also run from the environment $FED_DIR.
git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/BIGDATA_RELEASE_1_3_0@8099 8f7bc0f5-282e-0410-95e3-8d296e9bb460

diff --git a/src/resources/etc/init.d/bigdataHA b/src/resources/etc/init.d/bigdataHA
--- a/src/resources/etc/init.d/bigdataHA
+++ b/src/resources/etc/init.d/bigdataHA
@@ -31,7 +31,7 @@ else
         STRING=$1
         echo -n "$STRING "
         shift
-        "$@" && echo -n "[OK]" || echo -n "[FAILED]"
+        sudo -u bigdata -g bigdata "$@" && echo -n "[OK]" || echo -n "[FAILED]"
         rc=$?
         echo
         return $rc
@@ -59,6 +59,9 @@ if [ -z "$pidFile" ]; then
    echo $"$0 : environment not setup: pidFile is undefined"
    exit 1;
 fi
+
+cd $FED_DIR
+
 
 #
 # See how we were called.
